# filename                          installdir                                    mode
10-rescue-dhcp.network              /etc/systemd/network                          644
sshd_rescue.conf                    /etc/ssh/sshd_config.d                        644
rescue-setup.service                /etc/systemd/system                           644
autologin.conf                      /etc/systemd/system/getty@.service.d          644
logind-override.conf                /etc/systemd/logind.conf.d                    644
rescue-setup.sh                     /usr/local/bin                                755
rescue-init.sh                      /usr/local/bin                                755
bashrc                              /root                                         644
pve-chroot                          /usr/local/bin                                755
pve-umount                          /usr/local/bin                                755
motd                                /etc                                          644
rescue-ip.sh                        /etc/profile.d                                644
proxmox.sources                     /etc/apt/sources.list.d                       644
proxmox-archive-keyring.gpg         /usr/share/keyrings                           644
