# link                                                                target
/etc/systemd/system/multi-user.target.wants/systemd-networkd.service /lib/systemd/system/systemd-networkd.service
/etc/systemd/system/multi-user.target.wants/systemd-resolved.service /lib/systemd/system/systemd-resolved.service
/etc/systemd/system/multi-user.target.wants/rescue-setup.service     /etc/systemd/system/rescue-setup.service
